# Generated by Django 4.2.5 on 2023-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('book_gender', models.CharField(choices=[('RM', 'Roman'), ('NV', 'Nouvelle'), ('PT', 'Pièce de théatre'), ('PS', 'Poésie')], max_length=2)),
            ],
            options={
                'verbose_name': 'livre',
                'verbose_name_plural': 'livres',
                'db_table': 'livres',
                'managed': True,
            },
        ),
    ]
