# Generated by Django 4.2.5 on 2023-09-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_options_alter_author_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='author',
            name='phome',
            field=models.CharField(max_length=20),
        ),
    ]
