# Generated by Django 4.2.5 on 2023-09-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_email_alter_author_phome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='phome',
            new_name='phone',
        ),
    ]
